version: '1'

services:
  mongo:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      -  mongo-config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ialfper
      - MONGO_INITDB_ROOT_PASSWORD=ialfper21

  web:
        image: mimagen:latest
        depends_on:
            - mongo
        environment:
            - PORT=5000
            - MONGO_URI="mongodb://ialfper:ialfper21@localhost:27017/?directConnection=true"
            - DDBB_NAME=despliegue
        ports:
            - 5000:5000

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local




