name: Crear y subir imagen Docker

on:
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Construir imagen
        run: docker build -t ivaniap/ejemploApiClientes:latest .

      - name: Subir imagen a Docker Hub
        run: docker push ivaniap/ejemploApiClientes:latest
