name: Crear y subir imagen Docker

on:
  push:
    branches:
      - main  # Se ejecutará cuando haya un push en la rama "main"

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir imagen
        run: docker build -t ivaniap/ejemploautomatico:latest .

      - name: Subir imagen a Docker Hub
        run: docker push ivaniap/ejemploautomatico:latest
