name: Crear y subir imagen docker
on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: construir imagen
          run: docker buildt -t ivaniap/ejemploApiClientes:latest .

        - name: subir imagen a dockerhub 
          run: docker push ivaniap/ejemploApiClientes:latest